# Generated by Django 4.2.16 on 2024-09-18 11:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_booking_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='service',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
