# Generated by Django 4.2.16 on 2024-09-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_booking_featured_image_service_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('Painting', 'Painting - Price from £100'), ('Assembling', 'Assembling Furniture and Units - Price from £50'), ('Packing & Moving', 'Packing & Moving - Price from £100')], max_length=100),
        ),
    ]
